name: "Trading_Interface"
main: ua.leonidius.trdinterface.Trading
version: "1.1.0"
author: Leonidius20
url: github.com/Leonidius20/TradingInterface
api: ["1.0.8"]
description: Shop system based on interface.
permissions:
  shop.edit:
    description: Editing lists of buyable and sellable items and discounts.
    default: op
depend:
  - EconomyAPI
  - DbLib