name: "Trading_Interface"
main: ua.leonidius.trdinterface.Trading
version: ${project.version}
author: Leondius20
url: ${project.url}
api: ["1.0.8"]
description: Shop system based on interface.
permissions:
  shop.edit:
    description: Editing lists of buyable and sellable items and discounts.
    default: op
depend:
  - EconomyAPI
  - DbLib